[build.env]
passthrough = [
  "PYAPP_DISTRIBUTION_EMBED",
  "PYAPP_DISTRIBUTION_FORMAT",
  "PYAPP_DISTRIBUTION_PYTHON_PATH",
  "PYAPP_DISTRIBUTION_SOURCE",
  "PYAPP_DISTRIBUTION_VARIANT",
  "PYAPP_EXEC_CODE",
  "PYAPP_EXEC_MODULE",
  "PYAPP_EXEC_SPEC",
  "PYAPP_PASS_LOCATION",
  "PYAPP_PROJECT_NAME",
  "PYAPP_PROJECT_VERSION",
  "PYAPP_SELF_COMMAND",
  "PYAPP_SKIP_INSTALL",
  "PYAPP_STARSHIP_PROMPT",
]
